## Broadcasting Rules

When dealing with distributions of different shapes, we very often encounter a situation where two distributions have different shapes. When this occurs, tensorflow_probability follows Numpy's braodcasting rules.

In [2]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

print("TF version:", tf.__version__)
print("TFP version:", tfp.__version__)


import numpy as np
print("Numpy version:", np.__version__)

TF version: 2.5.0
TFP version: 0.13.0
Numpy version: 1.21.2


## Operations on arrays of different sizes in numpy

Numpy operations can be applied to arrays that are not of the same shape, but only if the shapes satisfy certain conditions.

As a demonstration of this, let us add together two arrays of different shapes:

In [6]:
# Add two arrays with different shapes

a = np.array([[1.],
              [2.],
              [3.],
              [4.]])  # shape (4, 1)

b = np.array([0., 1., 2.])  # shape (3,) 

print("Shape of a and b : ",a.shape, b.shape)
result = a + b
print("Shape of result : ",result.shape)
print(result)

Shape of a and b :  (4, 1) (3,)
Shape of result :  (4, 3)
[[1. 2. 3.]
 [2. 3. 4.]
 [3. 4. 5.]
 [4. 5. 6.]]
